// Code generated by ogen, DO NOT EDIT.

package talentrbac

// HasPermissionParams is parameters of HasPermission operation.
type HasPermissionParams struct {
	PermissionID int32
	UserID       int32
}

// PermissionMetaParams is parameters of PermissionMeta operation.
type PermissionMetaParams struct {
	PermissionKey string
}
