// Code generated by ogen, DO NOT EDIT.

package talentrbac

// OperationName is the ogen operation name
type OperationName = string

const (
	HasPermissionOperation  OperationName = "HasPermission"
	PermissionMetaOperation OperationName = "PermissionMeta"
)
