// Code generated by ogen, DO NOT EDIT.

package talentrbac

import (
	"time"
)

// HasPermissionForbidden is response for HasPermission operation.
type HasPermissionForbidden struct{}

func (*HasPermissionForbidden) hasPermissionRes() {}

// HasPermissionOK is response for HasPermission operation.
type HasPermissionOK struct{}

func (*HasPermissionOK) hasPermissionRes() {}

// Ref: #/components/responses/ObjectNotFound
type ObjectNotFound struct{}

func (*ObjectNotFound) permissionMetaRes() {}

// Ref: #/components/schemas/PermissionMeta
type PermissionMeta struct {
	// Идентификатор привилегии.
	ID int32 `json:"id"`
	// Дата создания.
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *PermissionMeta) GetID() int32 {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *PermissionMeta) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *PermissionMeta) SetID(val int32) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *PermissionMeta) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*PermissionMeta) permissionMetaRes() {}
