// Code generated by ogen, DO NOT EDIT.
package talentv2

type EventDiplomaRoleAddRes interface {
	eventDiplomaRoleAddRes()
}

type EventDiplomaSettingsCreateRes interface {
	eventDiplomaSettingsCreateRes()
}

type EventDiplomaSettingsReadRes interface {
	eventDiplomaSettingsReadRes()
}

type EventDiplomaSettingsUpdateRes interface {
	eventDiplomaSettingsUpdateRes()
}

type EventRetrieveRes interface {
	eventRetrieveRes()
}

type FileConfirmUploadRes interface {
	fileConfirmUploadRes()
}

type FileMetaReadRes interface {
	fileMetaReadRes()
}

type FileMetaUpdateRes interface {
	fileMetaUpdateRes()
}

type FileReadRes interface {
	fileReadRes()
}

type FileReferenceCreateRes interface {
	fileReferenceCreateRes()
}

type FileReferenceDeleteRes interface {
	fileReferenceDeleteRes()
}

type FileUploadRes interface {
	fileUploadRes()
}

type OrganizationSubjectCreateRes interface {
	organizationSubjectCreateRes()
}

type PersonReadRes interface {
	personReadRes()
}

type SocialAuthListRes interface {
	socialAuthListRes()
}

type TeamContactValidateRes interface {
	teamContactValidateRes()
}

type TeamReadRes interface {
	teamReadRes()
}

type TeamUpdateRes interface {
	teamUpdateRes()
}
