// Code generated by ogen, DO NOT EDIT.
package talentv2

type AddEventDiplomaRoleRes interface {
	addEventDiplomaRoleRes()
}

type ArchiveEventRequestsFilesRes interface {
	archiveEventRequestsFilesRes()
}

type CancelEventDeferredNotificationRes interface {
	cancelEventDeferredNotificationRes()
}

type CheckUserConsentRes interface {
	checkUserConsentRes()
}

type CompleteSocialAuthRes interface {
	completeSocialAuthRes()
}

type ConfirmFileUploadRes interface {
	confirmFileUploadRes()
}

type ConfirmSignupEmailRes interface {
	confirmSignupEmailRes()
}

type CreateEventDeferredNotificationRes interface {
	createEventDeferredNotificationRes()
}

type CreateEventDiplomaSettingsRes interface {
	createEventDiplomaSettingsRes()
}

type CreateEventLimitRes interface {
	createEventLimitRes()
}

type CreateEventRes interface {
	createEventRes()
}

type CreateFileMetaRes interface {
	createFileMetaRes()
}

type CreateFileReferenceRes interface {
	createFileReferenceRes()
}

type CreateMutationLockRes interface {
	createMutationLockRes()
}

type CreateOrganizationSubjectRes interface {
	createOrganizationSubjectRes()
}

type DeleteEventLimitRes interface {
	deleteEventLimitRes()
}

type DeleteFileReferenceRes interface {
	deleteFileReferenceRes()
}

type DeleteMutationLockRes interface {
	deleteMutationLockRes()
}

type DisconnectSocialAuthRes interface {
	disconnectSocialAuthRes()
}

type EventDeferredNotificationTemplateIDRes interface {
	eventDeferredNotificationTemplateIDRes()
}

type EventSignupRes interface {
	eventSignupRes()
}

type ExistsEventDeferredNotificationRes interface {
	existsEventDeferredNotificationRes()
}

type IsOrganizationAdminRes interface {
	isOrganizationAdminRes()
}

type IssueAccessTokenRes interface {
	issueAccessTokenRes()
}

type ListEventsRes interface {
	listEventsRes()
}

type ListFileMetaRes interface {
	listFileMetaRes()
}

type ListOrganizationsRes interface {
	listOrganizationsRes()
}

type ListSocialAuthsRes interface {
	listSocialAuthsRes()
}

type ListUserConsentsRes interface {
	listUserConsentsRes()
}

type LoginSocialAuthRes interface {
	loginSocialAuthRes()
}

type PatchMutationLockRes interface {
	patchMutationLockRes()
}

type ReadEventDeferredNotificationRes interface {
	readEventDeferredNotificationRes()
}

type ReadEventDiplomaSettingsRes interface {
	readEventDiplomaSettingsRes()
}

type ReadEventLimitRes interface {
	readEventLimitRes()
}

type ReadEventRes interface {
	readEventRes()
}

type ReadFileMetaRes interface {
	readFileMetaRes()
}

type ReadFileRes interface {
	readFileRes()
}

type ReadPersonRes interface {
	readPersonRes()
}

type ReadTeamRes interface {
	readTeamRes()
}

type SignupInitialDataRes interface {
	signupInitialDataRes()
}

type SignupRes interface {
	signupRes()
}

type SubmitUserConsentRes interface {
	submitUserConsentRes()
}

type UpdateAuthenticatedUserRes interface {
	updateAuthenticatedUserRes()
}

type UpdateEventDeferredNotificationRes interface {
	updateEventDeferredNotificationRes()
}

type UpdateEventDiplomaSettingsRes interface {
	updateEventDiplomaSettingsRes()
}

type UpdateEventLimitRes interface {
	updateEventLimitRes()
}

type UpdateFileMetaRes interface {
	updateFileMetaRes()
}

type UpdateTeamRes interface {
	updateTeamRes()
}

type UploadFileRes interface {
	uploadFileRes()
}

type ValidateTeamContactRes interface {
	validateTeamContactRes()
}
