// Code generated by ogen, DO NOT EDIT.

package talentv2

import (
	"github.com/google/uuid"
)

// AddEventDiplomaRoleParams is parameters of AddEventDiplomaRole operation.
type AddEventDiplomaRoleParams struct {
	// ID мероприятия.
	EventID int32
	// ID роли достижения.
	RoleID int32
}

// ArchiveEventRequestsFilesParams is parameters of ArchiveEventRequestsFiles operation.
type ArchiveEventRequestsFilesParams struct {
	FieldID   OptInt32 `json:",omitempty,omitzero"`
	RequestID OptInt32 `json:",omitempty,omitzero"`
	// ID мероприятия.
	EventID int32
}

// CancelEventDeferredNotificationParams is parameters of CancelEventDeferredNotification operation.
type CancelEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// CheckUserConsentParams is parameters of CheckUserConsent operation.
type CheckUserConsentParams struct {
	// ID пользователя.
	TalentID int32
	Kind     UserConsentKind
}

// CityNameParams is parameters of CityName operation.
type CityNameParams struct {
	Fias uuid.UUID
}

// CompleteSocialAuthParams is parameters of CompleteSocialAuth operation.
type CompleteSocialAuthParams struct {
	Provider  string
	State     string
	CsrfState OptString `json:",omitempty,omitzero"`
}

// ConfirmEventSignupParams is parameters of ConfirmEventSignup operation.
type ConfirmEventSignupParams struct {
	// Валидация запроса без подтверждения заявки.
	DryRun         OptBool `json:",omitempty,omitzero"`
	EventRequestID string
	Token          string
}

// ConfirmFileUploadParams is parameters of ConfirmFileUpload operation.
type ConfirmFileUploadParams struct {
	// ID файла.
	FileID uuid.UUID
}

// ConfirmSignupEmailParams is parameters of ConfirmSignupEmail operation.
type ConfirmSignupEmailParams struct {
	UID   string
	Token string
}

// CountEventsParams is parameters of CountEvents operation.
type CountEventsParams struct {
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32 `json:",omitempty"`
	// Фильтрация мероприятий по ID организации.
	OrganizationID []int32 `json:",omitempty"`
	// Фильтрация мероприятий по ID мета-мероприятия.
	MetaEventID []int32 `json:",omitempty"`
	// Фильтрация мероприятий по ID площадки их проведения.
	VenueID []int32 `json:",omitempty"`
	// Мероприятия с датой начала ранее указанной.
	StartBefore OptDateTime `json:",omitempty,omitzero"`
	// Мероприятия с датой завершения после указанной.
	EndAfter OptDateTime `json:",omitempty,omitzero"`
	// Поиск по названию, ключевым словам и описанию.
	Search OptString `json:",omitempty,omitzero"`
	// Фильтрация по формату мероприятий.
	Format OptEventFormat `json:",omitempty,omitzero"`
}

// CreateEventDeferredNotificationParams is parameters of CreateEventDeferredNotification operation.
type CreateEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// CreateEventDiplomaSettingsParams is parameters of CreateEventDiplomaSettings operation.
type CreateEventDiplomaSettingsParams struct {
	// ID мероприятия.
	EventID int32
}

// CreateEventLimitParams is parameters of CreateEventLimit operation.
type CreateEventLimitParams struct {
	// ID мероприятия.
	EventID int32
}

// CreateEventTeamParams is parameters of CreateEventTeam operation.
type CreateEventTeamParams struct {
	// ID мероприятия.
	EventID int32
}

// CreateEventTeamPersonParams is parameters of CreateEventTeamPerson operation.
type CreateEventTeamPersonParams struct {
	// ID мероприятия.
	EventID int32
	// ID команды.
	TeamID int32
}

// CreateFileReferenceParams is parameters of CreateFileReference operation.
type CreateFileReferenceParams struct {
	// ID файла.
	FileID uuid.UUID
	// ID связанного объекта.
	ObjectID string
}

// CreateMutationLockParams is parameters of CreateMutationLock operation.
type CreateMutationLockParams struct {
	// Имя пространства имен, к которому относится зависимый
	// объект.
	ObjectNamespace string
	// Ключ объекта зависящего от блокируемых файлов.
	ObjectKey string
}

// CreateUserTeamPersonParams is parameters of CreateUserTeamPerson operation.
type CreateUserTeamPersonParams struct {
	// ID команды.
	TeamID int32
}

// DeleteEventDiplomaRoleParams is parameters of DeleteEventDiplomaRole operation.
type DeleteEventDiplomaRoleParams struct {
	// ID мероприятия.
	EventID int32
	// ID роли достижения.
	RoleID int32
}

// DeleteEventLimitParams is parameters of DeleteEventLimit operation.
type DeleteEventLimitParams struct {
	// ID мероприятия.
	EventID int32
}

// DeleteFileReferenceParams is parameters of DeleteFileReference operation.
type DeleteFileReferenceParams struct {
	// ID файла.
	FileID uuid.UUID
	// ID связанного объекта.
	ObjectID string
}

// DeleteMutationLockParams is parameters of DeleteMutationLock operation.
type DeleteMutationLockParams struct {
	// Имя пространства имен, к которому относится зависимый
	// объект.
	ObjectNamespace string
	// Ключ объекта зависящего от блокируемых файлов.
	ObjectKey string
}

// DisconnectSocialAuthParams is parameters of DisconnectSocialAuth operation.
type DisconnectSocialAuthParams struct {
	Provider string
	// Внешний идентификатор пользователя.
	UID string
}

// EventDeferredNotificationTemplateIDParams is parameters of EventDeferredNotificationTemplateID operation.
type EventDeferredNotificationTemplateIDParams struct {
	Name string
}

// EventSignupParams is parameters of EventSignup operation.
type EventSignupParams struct {
	// Валидация запроса без создания заявки.
	DryRun OptBool `json:",omitempty,omitzero"`
	// Отключение уведомления пользователя о регистрации.
	SilenceNotification OptBool   `json:",omitempty,omitzero"`
	AcceptLanguage      OptString `json:",omitempty,omitzero"`
	Utm                 OptString `json:",omitempty,omitzero"`
	// ID мероприятия.
	EventID int32
}

// ExistsEventDeferredNotificationParams is parameters of ExistsEventDeferredNotification operation.
type ExistsEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// IsOrganizationAdminParams is parameters of IsOrganizationAdmin operation.
type IsOrganizationAdminParams struct {
	// ID организации.
	OrganizationID int32
	// Требование наличия или отсутствия статуса владельца
	// организации.
	//
	// При указании значения, роль пользователя должна ему
	// соответствовать; это значит что если указать `false`, а
	// пользователь является владельцем, то ответ будет
	// иметь статус `403`.
	IsOwner OptBool `json:",omitempty,omitzero"`
}

// IsTeamOwnerParams is parameters of IsTeamOwner operation.
type IsTeamOwnerParams struct {
	// ID команды.
	TeamID int32
}

// ListAddAchievementEventsParams is parameters of ListAddAchievementEvents operation.
type ListAddAchievementEventsParams struct {
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Поиск по названию, ключевым словам и описанию.
	Search OptString `json:",omitempty,omitzero"`
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32 `json:",omitempty"`
	// Фильтрация по формату мероприятий.
	Format OptEventFormat `json:",omitempty,omitzero"`
	// Мероприятия с датой начала ранее указанной.
	StartBefore OptDateTime `json:",omitempty,omitzero"`
	// Мероприятия с датой завершения после указанной.
	EndAfter OptDateTime `json:",omitempty,omitzero"`
	// Фильтр по массиву идентификаторов брендов.
	BrandID []int32 `json:",omitempty"`
	// Фильтр по массиву идентификаторов компетенций
	// Конкурса Талант.
	CompetencyID []int32 `json:",omitempty"`
	// Фильтрация по названию региона.
	Region OptString `json:",omitempty,omitzero"`
}

// ListCalendarEventsParams is parameters of ListCalendarEvents operation.
type ListCalendarEventsParams struct {
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Критерий сортировки результатов.
	OrderBy OptListCalendarEventsOrderBy `json:",omitempty,omitzero"`
}

// ListEventBrandsParams is parameters of ListEventBrands operation.
type ListEventBrandsParams struct {
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32 `json:",omitempty"`
	// Фильтр по массиву идентификаторов брендов.
	BrandID []int32 `json:",omitempty"`
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// ListEventDiplomaSettingsParams is parameters of ListEventDiplomaSettings operation.
type ListEventDiplomaSettingsParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// ID мероприятий, записывается в формате `?event_ids=1,2,3`.
	EventIds []int32 `json:",omitempty"`
}

// ListEventFieldsParams is parameters of ListEventFields operation.
type ListEventFieldsParams struct {
	// ID мероприятия.
	EventID int32
}

// ListEventRoutesParams is parameters of ListEventRoutes operation.
type ListEventRoutesParams struct {
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32 `json:",omitempty"`
	// Фильтр по массиву идентификаторов направлений.
	RouteID []int32 `json:",omitempty"`
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// ListEventsParams is parameters of ListEvents operation.
type ListEventsParams struct {
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32 `json:",omitempty"`
	// Фильтрация мероприятий по ID организации.
	OrganizationID []int32 `json:",omitempty"`
	// Фильтрация мероприятий по ID мета-мероприятия.
	MetaEventID []int32 `json:",omitempty"`
	// Фильтрация мероприятий по ID площадки их проведения.
	VenueID []int32 `json:",omitempty"`
	// Мероприятия с датой начала ранее указанной.
	StartBefore OptDateTime `json:",omitempty,omitzero"`
	// Мероприятия с датой завершения после указанной.
	EndAfter OptDateTime `json:",omitempty,omitzero"`
	// Поиск по названию, ключевым словам и описанию.
	Search OptString `json:",omitempty,omitzero"`
	// Фильтрация по формату мероприятий.
	Format OptEventFormat `json:",omitempty,omitzero"`
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit   OptInt32             `json:",omitempty,omitzero"`
	OrderBy OptListEventsOrderBy `json:",omitempty,omitzero"`
}

// ListFileMetaParams is parameters of ListFileMeta operation.
type ListFileMetaParams struct {
	// Чтение метаинформации конкретных файлов. Значения
	// указываются через запятую.
	FileID []uuid.UUID `json:",omitempty"`
	// Статус публичности файла.
	IsPublic OptBool `json:",omitempty,omitzero"`
	// Пространство имен для объекта, где используется файл,
	// в формате <сервис>/<таблица БД>/<поле со ссылкой на файл>
	// (например, polls/questions/picture, venues/venue/cover, etc.).
	Namespace OptString `json:",omitempty,omitzero"`
	// Фильтрация по префиксной подстроке в пространстве
	// имен.
	NamespaceStartswith OptString `json:",omitempty,omitzero"`
	// Фильтрация по подстроке в имени файла.
	NameLike OptString `json:",omitempty,omitzero"`
	// Фильтрация по точному совпадению расширения.
	Ext OptString `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Поле, по которому будет отсортирован список файлов.
	OrderBy OptListFileMetaOrderBy `json:",omitempty,omitzero"`
}

// ListOrganizationEventsParams is parameters of ListOrganizationEvents operation.
type ListOrganizationEventsParams struct {
	// ID организации.
	OrganizationID int32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32 `json:",omitempty"`
	// Поиск по названию, ключевым словам и описанию.
	Search OptString `json:",omitempty,omitzero"`
	// Фильтрация по формату мероприятий.
	Format OptEventFormat `json:",omitempty,omitzero"`
	// Мероприятия с датой начала ранее указанной.
	StartBefore OptDateTime `json:",omitempty,omitzero"`
	// Мероприятия с датой завершения после указанной.
	EndAfter OptDateTime `json:",omitempty,omitzero"`
	// Фильтрация по названию города.
	City OptString `json:",omitempty,omitzero"`
	// Критерий сортировки результатов.
	//
	// При использовании текстового поиска, результаты будут
	// отсортированы сначала в порядке релевантности, а
	// потом в соответствии с указанным этим параметром
	// критерием.
	OrderBy OptListOrganizationEventsOrderBy `json:",omitempty,omitzero"`
}

// ListOrganizationSubjectsParams is parameters of ListOrganizationSubjects operation.
type ListOrganizationSubjectsParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Фильтр по массиву идентификаторов организаций.
	OrganizationID []int32 `json:",omitempty"`
	// Фильтр по массиву идентификаторов тематик.
	SubjectID []int32 `json:",omitempty"`
}

// ListOrganizationsParams is parameters of ListOrganizations operation.
type ListOrganizationsParams struct {
	// Фильтр по массиву идентификаторов организаций.
	OrganizationID []int32 `json:",omitempty"`
	// ID родительской организации.
	ParentOrganizationID OptInt32 `json:",omitempty,omitzero"`
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Критерий сортировки результатов.
	OrderBy OptListOrganizationsOrderBy `json:",omitempty,omitzero"`
}

// ListSocialAuthsParams is parameters of ListSocialAuths operation.
type ListSocialAuthsParams struct {
	// Фильтрация по провайдеру авторизации.
	Provider OptSocialAuthProvider `json:",omitempty,omitzero"`
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// ID пользователя.
	TalentID int32
}

// ListSubjectsParams is parameters of ListSubjects operation.
type ListSubjectsParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32 `json:",omitempty,omitzero"`
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// ListTeamsParams is parameters of ListTeams operation.
type ListTeamsParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32 `json:",omitempty,omitzero"`
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Фильтрация по массиву идентификаторов команд.
	ID []int32 `json:",omitempty"`
	// Критерий сортировки результатов.
	OrderBy OptListTeamsOrderBy `json:",omitempty,omitzero"`
}

// ListUserConsentsParams is parameters of ListUserConsents operation.
type ListUserConsentsParams struct {
	// ID пользователя.
	TalentID int32
}

// LoginSocialAuthParams is parameters of LoginSocialAuth operation.
type LoginSocialAuthParams struct {
	Provider string
	Next     OptString `json:",omitempty,omitzero"`
	RegNext  OptString `json:",omitempty,omitzero"`
	ErrNext  OptString `json:",omitempty,omitzero"`
}

// PatchMutationLockParams is parameters of PatchMutationLock operation.
type PatchMutationLockParams struct {
	// Имя пространства имен, к которому относится зависимый
	// объект.
	ObjectNamespace string
	// Ключ объекта зависящего от блокируемых файлов.
	ObjectKey string
}

// ReadEventParams is parameters of ReadEvent operation.
type ReadEventParams struct {
	// Вернуть в ответе полный набор свойств.
	Extend OptBool `json:",omitempty,omitzero"`
	// ID мероприятия.
	EventID int32
}

// ReadEventDeferredNotificationParams is parameters of ReadEventDeferredNotification operation.
type ReadEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// ReadEventDiplomaSettingsParams is parameters of ReadEventDiplomaSettings operation.
type ReadEventDiplomaSettingsParams struct {
	// ID мероприятия.
	EventID int32
}

// ReadEventLimitParams is parameters of ReadEventLimit operation.
type ReadEventLimitParams struct {
	// ID мероприятия.
	EventID int32
}

// ReadEventRequestParams is parameters of ReadEventRequest operation.
type ReadEventRequestParams struct {
	EventRequestID int32
	Fields         OptBool `json:",omitempty,omitzero"`
}

// ReadEventTeamParams is parameters of ReadEventTeam operation.
type ReadEventTeamParams struct {
	// ID мероприятия.
	EventID int32
	// ID команды.
	TeamID int32
}

// ReadFileParams is parameters of ReadFile operation.
type ReadFileParams struct {
	Noredir OptBool `json:",omitempty,omitzero"`
	// ID файла.
	FileID uuid.UUID
}

// ReadFileMetaParams is parameters of ReadFileMeta operation.
type ReadFileMetaParams struct {
	// ID файла.
	FileID uuid.UUID
}

// ReadGeoDataParams is parameters of ReadGeoData operation.
type ReadGeoDataParams struct {
	GeodataID int32
}

// ReadPersonParams is parameters of ReadPerson operation.
type ReadPersonParams struct {
	// ID персоны.
	PersonID int32
}

// ReadTeamParams is parameters of ReadTeam operation.
type ReadTeamParams struct {
	// Включить в ответ массив участников команды.
	Persons OptBool `json:",omitempty,omitzero"`
	// ID команды.
	TeamID int32
}

// ReadUserTeamParams is parameters of ReadUserTeam operation.
type ReadUserTeamParams struct {
	// ID команды.
	TeamID int32
}

// RegionNameParams is parameters of RegionName operation.
type RegionNameParams struct {
	Fias uuid.UUID
}

// SignupParams is parameters of Signup operation.
type SignupParams struct {
	PartialToken OptUUID   `json:",omitempty,omitzero"`
	Utm          OptString `json:",omitempty,omitzero"`
}

// SignupInitialDataParams is parameters of SignupInitialData operation.
type SignupInitialDataParams struct {
	PartialToken uuid.UUID
}

// SubmitUserConsentParams is parameters of SubmitUserConsent operation.
type SubmitUserConsentParams struct {
	// ID пользователя.
	TalentID int32
	Kind     UserConsentKind
}

// SuggestGeoFieldParams is parameters of SuggestGeoField operation.
type SuggestGeoFieldParams struct {
	Field SuggestGeoFieldField
	Term  string
}

// UpdateEventParams is parameters of UpdateEvent operation.
type UpdateEventParams struct {
	// ID мероприятия.
	EventID int32
}

// UpdateEventDeferredNotificationParams is parameters of UpdateEventDeferredNotification operation.
type UpdateEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// UpdateEventDiplomaSettingsParams is parameters of UpdateEventDiplomaSettings operation.
type UpdateEventDiplomaSettingsParams struct {
	// ID мероприятия.
	EventID int32
}

// UpdateEventLimitParams is parameters of UpdateEventLimit operation.
type UpdateEventLimitParams struct {
	// ID мероприятия.
	EventID int32
}

// UpdateEventRequestParams is parameters of UpdateEventRequest operation.
type UpdateEventRequestParams struct {
	EventRequestID int32
	Fields         OptBool `json:",omitempty,omitzero"`
}

// UpdateEventTeamParams is parameters of UpdateEventTeam operation.
type UpdateEventTeamParams struct {
	// ID мероприятия.
	EventID int32
	// ID команды.
	TeamID int32
}

// UpdateEventTeamPersonParams is parameters of UpdateEventTeamPerson operation.
type UpdateEventTeamPersonParams struct {
	// ID мероприятия.
	EventID int32
	// ID команды.
	TeamID int32
	// ID участника команды.
	TeamPersonID int32
}

// UpdateFileMetaParams is parameters of UpdateFileMeta operation.
type UpdateFileMetaParams struct {
	// ID файла.
	FileID uuid.UUID
}

// UpdateOwnerTeamPersonParams is parameters of UpdateOwnerTeamPerson operation.
type UpdateOwnerTeamPersonParams struct {
	// ID команды.
	TeamID int32
	// ID участника команды.
	TeamPersonID int32
}

// UpdateUserTeamParams is parameters of UpdateUserTeam operation.
type UpdateUserTeamParams struct {
	// ID команды.
	TeamID int32
}

// UpdateUserTeamPersonParams is parameters of UpdateUserTeamPerson operation.
type UpdateUserTeamPersonParams struct {
	// ID команды.
	TeamID int32
}

// UploadFileParams is parameters of UploadFile operation.
type UploadFileParams struct {
	// ID файла.
	FileID uuid.UUID
}

// ValidateAuthorizationParams is parameters of ValidateAuthorization operation.
type ValidateAuthorizationParams struct {
	ResponseType string
	RedirectURI  string
	ClientID     string
	Scope        OptString `json:",omitempty,omitzero"`
	AutoRenew    OptBool   `json:",omitempty,omitzero"`
}
