// Code generated by ogen, DO NOT EDIT.

package talentv2

// OperationName is the ogen operation name
type OperationName = string

const (
	AddAchievementEventListOperation    OperationName = "AddAchievementEventList"
	CalendarEventListOperation          OperationName = "CalendarEventList"
	EventBrandListOperation             OperationName = "EventBrandList"
	EventCountOperation                 OperationName = "EventCount"
	EventDiplomaRoleAddOperation        OperationName = "EventDiplomaRoleAdd"
	EventDiplomaRoleDeleteOperation     OperationName = "EventDiplomaRoleDelete"
	EventDiplomaSettingsCreateOperation OperationName = "EventDiplomaSettingsCreate"
	EventDiplomaSettingsListOperation   OperationName = "EventDiplomaSettingsList"
	EventDiplomaSettingsReadOperation   OperationName = "EventDiplomaSettingsRead"
	EventDiplomaSettingsUpdateOperation OperationName = "EventDiplomaSettingsUpdate"
	EventListOperation                  OperationName = "EventList"
	EventRetrieveOperation              OperationName = "EventRetrieve"
	EventRouteListOperation             OperationName = "EventRouteList"
	FileConfirmUploadOperation          OperationName = "FileConfirmUpload"
	FileMetaCreateOperation             OperationName = "FileMetaCreate"
	FileMetaListOperation               OperationName = "FileMetaList"
	FileMetaReadOperation               OperationName = "FileMetaRead"
	FileMetaUpdateOperation             OperationName = "FileMetaUpdate"
	FileReadOperation                   OperationName = "FileRead"
	FileReferenceCreateOperation        OperationName = "FileReferenceCreate"
	FileReferenceDeleteOperation        OperationName = "FileReferenceDelete"
	FileUploadOperation                 OperationName = "FileUpload"
	OrganizationEventListOperation      OperationName = "OrganizationEventList"
	OrganizationIsAdminOperation        OperationName = "OrganizationIsAdmin"
	OrganizationListOperation           OperationName = "OrganizationList"
	OrganizationSubjectCreateOperation  OperationName = "OrganizationSubjectCreate"
	OrganizationSubjectListOperation    OperationName = "OrganizationSubjectList"
	PersonReadOperation                 OperationName = "PersonRead"
	SocialAuthListOperation             OperationName = "SocialAuthList"
	SubjectListOperation                OperationName = "SubjectList"
	TeamContactValidateOperation        OperationName = "TeamContactValidate"
	TeamReadOperation                   OperationName = "TeamRead"
	TeamUpdateOperation                 OperationName = "TeamUpdate"
)
