// Code generated by ogen, DO NOT EDIT.

package talentv2

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ClientCredentials provides ClientCredentials security value.
	// Аутентификация учетными данными OAuth2 клиента TalentOAuth.
	ClientCredentials(ctx context.Context, operationName OperationName) (ClientCredentials, error)
	// TalentOAuth provides TalentOAuth security value.
	// Аутентификация токеном TalentOAuth пользователем Таланта.
	TalentOAuth(ctx context.Context, operationName OperationName) (TalentOAuth, error)
}

// operationRolesClientCredentials is a private map storing roles per operation.
var operationRolesClientCredentials = map[string][]string{
	DeleteMutationLockOperation: []string{},
	ListSocialAuthsOperation:    []string{},
	PatchMutationLockOperation:  []string{},
}

// GetRolesForClientCredentials returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForClientCredentials(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForClientCredentials(operation string) []string {
	roles, ok := operationRolesClientCredentials[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesTalentOAuth is a private map storing roles per operation.
var operationRolesTalentOAuth = map[string][]string{
	AddEventDiplomaRoleOperation: []string{
		"events",
	},
	AdminCreateEventOperation: []string{
		"admin:events-write",
	},
	AdminCreateEventLimitOperation: []string{
		"admin:events-write",
	},
	AdminDeleteEventLimitOperation: []string{
		"admin:events-write",
	},
	AdminUpdateEventOperation: []string{
		"admin:events-write",
	},
	AdminUpdateEventLimitOperation: []string{
		"admin:events-write",
	},
	ArchiveEventRequestsFilesOperation: []string{
		"events",
	},
	AuthorizeClientOperation: []string{},
	CancelEventDeferredNotificationOperation: []string{
		"events",
	},
	CheckUserConsentOperation: []string{
		"user:read",
	},
	ConfirmFileUploadOperation: []string{
		"files",
	},
	CreateEventOperation: []string{
		"events",
	},
	CreateEventDeferredNotificationOperation: []string{
		"events",
	},
	CreateEventDiplomaSettingsOperation: []string{
		"events",
	},
	CreateEventLimitOperation: []string{
		"events",
	},
	CreateEventTeamOperation: []string{
		"events",
	},
	CreateEventTeamPersonOperation: []string{
		"events",
	},
	CreateFileMetaOperation: []string{
		"files",
	},
	CreateFileReferenceOperation: []string{
		"files",
	},
	CreateMutationLockOperation: []string{
		"files",
	},
	CreateOrganizationSubjectOperation: []string{
		"events",
	},
	CreateUserTeamOperation: []string{
		"teams",
	},
	CreateUserTeamPersonOperation: []string{
		"teams",
	},
	DeleteEventDiplomaRoleOperation: []string{
		"events",
	},
	DeleteEventLimitOperation: []string{
		"events",
	},
	DeleteFileReferenceOperation: []string{
		"files",
	},
	DeleteUserTeamOperation: []string{
		"teams",
	},
	DisconnectSocialAuthOperation: []string{
		"user",
	},
	EventSignupOperation: []string{
		"event-requests",
	},
	IsOrganizationAdminOperation: []string{},
	IsTeamOwnerOperation: []string{
		"teams:read",
	},
	ListEventDiplomaSettingsOperation: []string{
		"events:read",
	},
	ListFileMetaOperation: []string{
		"files:read",
	},
	ListSocialAuthsOperation: []string{
		"user:read",
	},
	ListTeamsOperation: []string{},
	ListUserConsentsOperation: []string{
		"user:read",
	},
	ListUserTeamPersonsOperation: []string{
		"teams",
	},
	ListUserTeamsOperation: []string{
		"teams:read",
	},
	ReadEventDeferredNotificationOperation: []string{
		"events:read",
	},
	ReadEventDiplomaSettingsOperation: []string{
		"events:read",
	},
	ReadEventRequestOperation: []string{
		"event-requests",
	},
	ReadEventTeamOperation: []string{
		"events:read",
	},
	ReadFileOperation:     []string{},
	ReadFileMetaOperation: []string{},
	ReadTeamOperation:     []string{},
	ReadUserTeamOperation: []string{
		"teams:read",
	},
	SubmitUserConsentOperation: []string{
		"user",
	},
	UpdateEventOperation: []string{
		"events",
	},
	UpdateEventDeferredNotificationOperation: []string{
		"events",
	},
	UpdateEventDiplomaSettingsOperation: []string{
		"events",
	},
	UpdateEventLimitOperation: []string{
		"events",
	},
	UpdateEventRequestOperation: []string{
		"event-requests",
	},
	UpdateEventTeamOperation: []string{
		"events",
	},
	UpdateEventTeamPersonOperation: []string{
		"teams",
	},
	UpdateFileMetaOperation: []string{
		"files",
	},
	UpdateOwnerTeamPersonOperation: []string{
		"teams",
	},
	UpdateUserTeamOperation: []string{
		"teams",
	},
	UpdateUserTeamPersonOperation: []string{
		"teams",
	},
	UploadFileOperation: []string{
		"files",
	},
	ValidateAuthorizationOperation: []string{},
}

// GetRolesForTalentOAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForTalentOAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForTalentOAuth(operation string) []string {
	roles, ok := operationRolesTalentOAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityClientCredentials(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ClientCredentials(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ClientCredentials\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
func (s *Client) securityTalentOAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TalentOAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TalentOAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
