// Code generated by ogen, DO NOT EDIT.

package talentv2

import (
	"github.com/google/uuid"
)

// AddEventDiplomaRoleParams is parameters of AddEventDiplomaRole operation.
type AddEventDiplomaRoleParams struct {
	// ID мероприятия.
	EventID int32
	// ID роли достижения.
	RoleID int32
}

// ArchiveEventRequestsFilesParams is parameters of ArchiveEventRequestsFiles operation.
type ArchiveEventRequestsFilesParams struct {
	FieldID   OptInt32
	RequestID OptInt32
	// ID мероприятия.
	EventID int32
}

// CancelEventDeferredNotificationParams is parameters of CancelEventDeferredNotification operation.
type CancelEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// CheckUserConsentParams is parameters of CheckUserConsent operation.
type CheckUserConsentParams struct {
	// ID пользователя.
	UserID int32
	Kind   UserConsentKind
}

// CompleteSocialAuthParams is parameters of CompleteSocialAuth operation.
type CompleteSocialAuthParams struct {
	Provider  string
	State     string
	CsrfState OptString
}

// ConfirmFileUploadParams is parameters of ConfirmFileUpload operation.
type ConfirmFileUploadParams struct {
	// ID файла.
	FileID uuid.UUID
}

// ConfirmSignupEmailParams is parameters of ConfirmSignupEmail operation.
type ConfirmSignupEmailParams struct {
	UID   string
	Token string
}

// CountEventsParams is parameters of CountEvents operation.
type CountEventsParams struct {
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32
	// Фильтрация мероприятий по ID организации.
	OrganizationID []int32
	// Фильтрация мероприятий по ID мета-мероприятия.
	MetaEventID []int32
	// Фильтрация мероприятий по ID площадки их проведения.
	VenueID []int32
	// Мероприятия с датой начала ранее указанной.
	StartBefore OptDateTime
	// Мероприятия с датой завершения после указанной.
	EndAfter OptDateTime
	// Поиск по названию, ключевым словам и описанию.
	Search OptString
	// Фильтрация по формату мероприятий.
	Format OptEventFormat
}

// CreateEventDeferredNotificationParams is parameters of CreateEventDeferredNotification operation.
type CreateEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// CreateEventDiplomaSettingsParams is parameters of CreateEventDiplomaSettings operation.
type CreateEventDiplomaSettingsParams struct {
	// ID мероприятия.
	EventID int32
}

// CreateEventLimitParams is parameters of CreateEventLimit operation.
type CreateEventLimitParams struct {
	// ID мероприятия.
	EventID int32
}

// CreateFileReferenceParams is parameters of CreateFileReference operation.
type CreateFileReferenceParams struct {
	// ID файла.
	FileID uuid.UUID
	// ID связанного объекта.
	ObjectID string
}

// CreateMutationLockParams is parameters of CreateMutationLock operation.
type CreateMutationLockParams struct {
	// Имя пространства имен, к которому относится
	// зависимый объект.
	ObjectNamespace string
	// Ключ объекта зависящего от блокируемых файлов.
	ObjectKey string
}

// DeleteEventDiplomaRoleParams is parameters of DeleteEventDiplomaRole operation.
type DeleteEventDiplomaRoleParams struct {
	// ID мероприятия.
	EventID int32
	// ID роли достижения.
	RoleID int32
}

// DeleteEventLimitParams is parameters of DeleteEventLimit operation.
type DeleteEventLimitParams struct {
	// ID мероприятия.
	EventID int32
}

// DeleteFileReferenceParams is parameters of DeleteFileReference operation.
type DeleteFileReferenceParams struct {
	// ID файла.
	FileID uuid.UUID
	// ID связанного объекта.
	ObjectID string
}

// DeleteMutationLockParams is parameters of DeleteMutationLock operation.
type DeleteMutationLockParams struct {
	// Имя пространства имен, к которому относится
	// зависимый объект.
	ObjectNamespace string
	// Ключ объекта зависящего от блокируемых файлов.
	ObjectKey string
}

// DisconnectSocialAuthParams is parameters of DisconnectSocialAuth operation.
type DisconnectSocialAuthParams struct {
	Provider string
	// Внешний идентификатор пользователя.
	UID string
}

// EventDeferredNotificationTemplateIDParams is parameters of EventDeferredNotificationTemplateID operation.
type EventDeferredNotificationTemplateIDParams struct {
	Name string
}

// EventSignupParams is parameters of EventSignup operation.
type EventSignupParams struct {
	// Валидация запроса без создания заявки.
	DryRun OptBool
	// Отключение уведомления пользователя о регистрации.
	SilenceNotification OptBool
	AcceptLanguage      OptString
	Utm                 OptString
	// ID мероприятия.
	EventID int32
}

// ExistsEventDeferredNotificationParams is parameters of ExistsEventDeferredNotification operation.
type ExistsEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// IsOrganizationAdminParams is parameters of IsOrganizationAdmin operation.
type IsOrganizationAdminParams struct {
	// ID организации.
	OrganizationID int32
	// Требование наличия или отсутствия статуса владельца
	// организации.
	// При указании значения, роль пользователя должна ему
	// соответствовать;
	// это значит что если указать `false`, а пользователь
	// является владельцем,
	// то ответ будет иметь статус `403`.
	IsOwner OptBool
}

// ListAddAchievementEventsParams is parameters of ListAddAchievementEvents operation.
type ListAddAchievementEventsParams struct {
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
	// Поиск по названию, ключевым словам и описанию.
	Search OptString
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32
	// Фильтрация по формату мероприятий.
	Format OptEventFormat
	// Мероприятия с датой начала ранее указанной.
	StartBefore OptDateTime
	// Мероприятия с датой завершения после указанной.
	EndAfter OptDateTime
	// Фильтр по массиву идентификаторов брендов.
	BrandID []int32
	// Фильтр по массиву идентификаторов компетенций
	// Конкурса Талант.
	CompetencyID []int32
	// Фильтрация по названию региона.
	Region OptString
}

// ListCalendarEventsParams is parameters of ListCalendarEvents operation.
type ListCalendarEventsParams struct {
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
	// Критерий сортировки результатов.
	OrderBy OptListCalendarEventsOrderBy
}

// ListEventBrandsParams is parameters of ListEventBrands operation.
type ListEventBrandsParams struct {
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32
	// Фильтр по массиву идентификаторов брендов.
	BrandID []int32
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
}

// ListEventDiplomaSettingsParams is parameters of ListEventDiplomaSettings operation.
type ListEventDiplomaSettingsParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
	// ID мероприятий, записывается в формате `?event_ids=1,2,3`.
	EventIds []int32
}

// ListEventFieldsParams is parameters of ListEventFields operation.
type ListEventFieldsParams struct {
	// ID мероприятия.
	EventID int32
}

// ListEventRoutesParams is parameters of ListEventRoutes operation.
type ListEventRoutesParams struct {
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32
	// Фильтр по массиву идентификаторов направлений.
	RouteID []int32
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
}

// ListEventsParams is parameters of ListEvents operation.
type ListEventsParams struct {
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32
	// Фильтрация мероприятий по ID организации.
	OrganizationID []int32
	// Фильтрация мероприятий по ID мета-мероприятия.
	MetaEventID []int32
	// Фильтрация мероприятий по ID площадки их проведения.
	VenueID []int32
	// Мероприятия с датой начала ранее указанной.
	StartBefore OptDateTime
	// Мероприятия с датой завершения после указанной.
	EndAfter OptDateTime
	// Поиск по названию, ключевым словам и описанию.
	Search OptString
	// Фильтрация по формату мероприятий.
	Format OptEventFormat
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit   OptInt32
	OrderBy OptListEventsOrderBy
}

// ListFileMetaParams is parameters of ListFileMeta operation.
type ListFileMetaParams struct {
	// Чтение метаинформации конкретных файлов. Значения
	// указываются через запятую.
	FileID []uuid.UUID
	// Статус публичности файла.
	IsPublic OptBool
	// Пространство имен для объекта, где используется файл,
	// в формате
	// <сервис>/<таблица БД>/<поле со ссылкой на файл>
	// (например, polls/questions/picture, venues/venue/cover, etc.).
	Namespace OptString
	// Фильтрация по префиксной подстроке в пространстве
	// имен.
	NamespaceStartswith OptString
	// Фильтрация по подстроке в имени файла.
	NameLike OptString
	// Фильтрация по точному совпадению расширения.
	Ext OptString
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
	// Поле, по которому будет отсортирован список файлов.
	OrderBy OptListFileMetaOrderBy
}

// ListOrganizationEventsParams is parameters of ListOrganizationEvents operation.
type ListOrganizationEventsParams struct {
	// ID организации.
	OrganizationID int32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
	// Фильтр по массиву идентификаторов мероприятий.
	EventID []int32
	// Поиск по названию, ключевым словам и описанию.
	Search OptString
	// Фильтрация по формату мероприятий.
	Format OptEventFormat
	// Мероприятия с датой начала ранее указанной.
	StartBefore OptDateTime
	// Мероприятия с датой завершения после указанной.
	EndAfter OptDateTime
	// Фильтрация по названию города.
	City OptString
	// Критерий сортировки результатов.
	// При использовании текстового поиска,
	// результаты будут отсортированы сначала в порядке
	// релевантности,
	// а потом в соответствии с указанным этим параметром
	// критерием.
	OrderBy OptListOrganizationEventsOrderBy
}

// ListOrganizationSubjectsParams is parameters of ListOrganizationSubjects operation.
type ListOrganizationSubjectsParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
	// Фильтр по массиву идентификаторов организаций.
	OrganizationID []int32
	// Фильтр по массиву идентификаторов тематик.
	SubjectID []int32
}

// ListOrganizationsParams is parameters of ListOrganizations operation.
type ListOrganizationsParams struct {
	// Фильтр по массиву идентификаторов организаций.
	OrganizationID []int32
	// ID родительской организации.
	ParentOrganizationID OptInt32
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
	// Критерий сортировки результатов.
	OrderBy OptListOrganizationsOrderBy
}

// ListSocialAuthsParams is parameters of ListSocialAuths operation.
type ListSocialAuthsParams struct {
	// Фильтрация по провайдеру авторизации.
	Provider OptSocialAuthProvider
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
	// ID пользователя.
	UserID int32
}

// ListSubjectsParams is parameters of ListSubjects operation.
type ListSubjectsParams struct {
	// Пропуск объектов с идентификатором равном или менее
	// указанного.
	IDOffset OptInt32
	// Кол-во объектов выборки для пропуска.
	Offset OptInt32
	// Максимум объектов возвращаемых в теле ответа.
	Limit OptInt32
}

// ListUserConsentsParams is parameters of ListUserConsents operation.
type ListUserConsentsParams struct {
	// ID пользователя.
	UserID int32
}

// LoginSocialAuthParams is parameters of LoginSocialAuth operation.
type LoginSocialAuthParams struct {
	Provider string
	Next     OptString
	RegNext  OptString
	ErrNext  OptString
}

// PatchMutationLockParams is parameters of PatchMutationLock operation.
type PatchMutationLockParams struct {
	// Имя пространства имен, к которому относится
	// зависимый объект.
	ObjectNamespace string
	// Ключ объекта зависящего от блокируемых файлов.
	ObjectKey string
}

// ReadEventParams is parameters of ReadEvent operation.
type ReadEventParams struct {
	// ID мероприятия.
	EventID int32
	// Вернуть в ответе полный набор свойств.
	Extend OptBool
}

// ReadEventDeferredNotificationParams is parameters of ReadEventDeferredNotification operation.
type ReadEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// ReadEventDiplomaSettingsParams is parameters of ReadEventDiplomaSettings operation.
type ReadEventDiplomaSettingsParams struct {
	// ID мероприятия.
	EventID int32
}

// ReadEventLimitParams is parameters of ReadEventLimit operation.
type ReadEventLimitParams struct {
	// ID мероприятия.
	EventID int32
}

// ReadFileParams is parameters of ReadFile operation.
type ReadFileParams struct {
	Noredir OptBool
	// ID файла.
	FileID uuid.UUID
}

// ReadFileMetaParams is parameters of ReadFileMeta operation.
type ReadFileMetaParams struct {
	// ID файла.
	FileID uuid.UUID
}

// ReadPersonParams is parameters of ReadPerson operation.
type ReadPersonParams struct {
	// ID персоны.
	PersonID int32
}

// ReadTeamParams is parameters of ReadTeam operation.
type ReadTeamParams struct {
	// ID команды.
	TeamID int32
}

// SignupParams is parameters of Signup operation.
type SignupParams struct {
	PartialToken OptUUID
	Utm          OptString
}

// SignupInitialDataParams is parameters of SignupInitialData operation.
type SignupInitialDataParams struct {
	PartialToken uuid.UUID
}

// SubmitUserConsentParams is parameters of SubmitUserConsent operation.
type SubmitUserConsentParams struct {
	// ID пользователя.
	UserID int32
	Kind   UserConsentKind
}

// UpdateEventDeferredNotificationParams is parameters of UpdateEventDeferredNotification operation.
type UpdateEventDeferredNotificationParams struct {
	// ID мероприятия.
	EventID int32
}

// UpdateEventDiplomaSettingsParams is parameters of UpdateEventDiplomaSettings operation.
type UpdateEventDiplomaSettingsParams struct {
	// ID мероприятия.
	EventID int32
}

// UpdateEventLimitParams is parameters of UpdateEventLimit operation.
type UpdateEventLimitParams struct {
	// ID мероприятия.
	EventID int32
}

// UpdateFileMetaParams is parameters of UpdateFileMeta operation.
type UpdateFileMetaParams struct {
	// ID файла.
	FileID uuid.UUID
}

// UpdateTeamParams is parameters of UpdateTeam operation.
type UpdateTeamParams struct {
	// ID команды.
	TeamID int32
}

// UploadFileParams is parameters of UploadFile operation.
type UploadFileParams struct {
	// ID файла.
	FileID uuid.UUID
}

// ValidateAuthorizationParams is parameters of ValidateAuthorization operation.
type ValidateAuthorizationParams struct {
	ResponseType string
	RedirectURI  string
	ClientID     string
	Scope        OptString
	AutoRenew    OptBool
}
