// Code generated by ogen, DO NOT EDIT.
package talentv2

type AddEventDiplomaRoleRes interface {
	addEventDiplomaRoleRes()
}

type ArchiveEventRequestsFilesRes interface {
	archiveEventRequestsFilesRes()
}

type CancelEventDeferredNotificationRes interface {
	cancelEventDeferredNotificationRes()
}

type CheckUserConsentRes interface {
	checkUserConsentRes()
}

type CityNameRes interface {
	cityNameRes()
}

type CompleteSocialAuthRes interface {
	completeSocialAuthRes()
}

type ConfirmEventSignupRes interface {
	confirmEventSignupRes()
}

type ConfirmFileUploadRes interface {
	confirmFileUploadRes()
}

type ConfirmSignupEmailRes interface {
	confirmSignupEmailRes()
}

type CreateEventDeferredNotificationRes interface {
	createEventDeferredNotificationRes()
}

type CreateEventDiplomaSettingsRes interface {
	createEventDiplomaSettingsRes()
}

type CreateEventLimitRes interface {
	createEventLimitRes()
}

type CreateEventRes interface {
	createEventRes()
}

type CreateEventTeamPersonRes interface {
	createEventTeamPersonRes()
}

type CreateEventTeamRes interface {
	createEventTeamRes()
}

type CreateFileMetaRes interface {
	createFileMetaRes()
}

type CreateFileReferenceRes interface {
	createFileReferenceRes()
}

type CreateMutationLockRes interface {
	createMutationLockRes()
}

type CreateOrganizationSubjectRes interface {
	createOrganizationSubjectRes()
}

type CreateUserTeamPersonRes interface {
	createUserTeamPersonRes()
}

type CreateUserTeamRes interface {
	createUserTeamRes()
}

type DeleteEventLimitRes interface {
	deleteEventLimitRes()
}

type DeleteFileReferenceRes interface {
	deleteFileReferenceRes()
}

type DeleteMutationLockRes interface {
	deleteMutationLockRes()
}

type DisconnectSocialAuthRes interface {
	disconnectSocialAuthRes()
}

type EventDeferredNotificationTemplateIDRes interface {
	eventDeferredNotificationTemplateIDRes()
}

type EventSignupRes interface {
	eventSignupRes()
}

type ExistsEventDeferredNotificationRes interface {
	existsEventDeferredNotificationRes()
}

type IsOrganizationAdminRes interface {
	isOrganizationAdminRes()
}

type IssueAccessTokenRes interface {
	issueAccessTokenRes()
}

type ListEventsRes interface {
	listEventsRes()
}

type ListFileMetaRes interface {
	listFileMetaRes()
}

type ListOrganizationsRes interface {
	listOrganizationsRes()
}

type ListSocialAuthsRes interface {
	listSocialAuthsRes()
}

type ListUserConsentsRes interface {
	listUserConsentsRes()
}

type LoginSocialAuthRes interface {
	loginSocialAuthRes()
}

type PatchMutationLockRes interface {
	patchMutationLockRes()
}

type ReadEventDeferredNotificationRes interface {
	readEventDeferredNotificationRes()
}

type ReadEventDiplomaSettingsRes interface {
	readEventDiplomaSettingsRes()
}

type ReadEventLimitRes interface {
	readEventLimitRes()
}

type ReadEventRequestRes interface {
	readEventRequestRes()
}

type ReadFileMetaRes interface {
	readFileMetaRes()
}

type ReadFileRes interface {
	readFileRes()
}

type ReadGeoDataRes interface {
	readGeoDataRes()
}

type RegionNameRes interface {
	regionNameRes()
}

type SignupInitialDataRes interface {
	signupInitialDataRes()
}

type SignupRes interface {
	signupRes()
}

type SubmitUserConsentRes interface {
	submitUserConsentRes()
}

type UpdateEventDeferredNotificationRes interface {
	updateEventDeferredNotificationRes()
}

type UpdateEventDiplomaSettingsRes interface {
	updateEventDiplomaSettingsRes()
}

type UpdateEventLimitRes interface {
	updateEventLimitRes()
}

type UpdateEventRequestRes interface {
	updateEventRequestRes()
}

type UpdateEventRes interface {
	updateEventRes()
}

type UpdateEventTeamRes interface {
	updateEventTeamRes()
}

type UpdateFileMetaRes interface {
	updateFileMetaRes()
}

type UpdateOwnerTeamPersonRes interface {
	updateOwnerTeamPersonRes()
}

type UpdateUserTeamPersonRes interface {
	updateUserTeamPersonRes()
}

type UpdateUserTeamRes interface {
	updateUserTeamRes()
}

type UploadFileRes interface {
	uploadFileRes()
}

type ValidateTeamContactRes interface {
	validateTeamContactRes()
}
