openapi: 3.1.0
info:
  title: Talent API v2
  version: '0.11-minor'
  contact:
    email: talent@kruzhok.org
servers:
  - url: https://talent.kruzhok.org/v2
    description: Production Server
  - url: https://talent.test.kruzhok.org/v2
    description: Development Server

tags:
  - name: generic-files
    x-displayName: Файлы любого формата
    description: |-
      Файлы пользователей могут быть как приватными так и публичными.
      Публичные файлы доступны всем, в том числе и без аутентификации.
      Запрос к приватному файлу может осуществляться только от его владельца.
      Так же как и запросы на какое либо изменение файла.

      Файлы могут быть загружены в хранилище и привязаны к объектам любого сервиса.
      Как загрузить файл:
      1. Выполнить запрос на создание файла с указанием пространства имен, где он будет использован. После
      успешного добавления метаинформации о файле в ответе будет получена ссылка на загрузку файла и ID файла.
      2. Загрузить файл в хранилище, используя полученный URL и заголовки.
      3. После успешной загрузки файла сообщить об этом серверу с помощью запроса
      [/files/{file_id}/confirm-upload](#tag/generic-files/operation/FileConfirmUpload) с указанием ID файла.
      4. При необходимости можно повторно получить ссылку на загрузку того же или альтернативного файла, отправив
      запрос на [/files/{file_id}](#tag/generic-files/operation/FileUpload) с указанием его размера.
      5. Для добавления ссылки на объект (ID в пространстве имен), где файл используется, нужно выполнить запрос
      [/files/{file_id}/references/{object_id}](#tag/generic-files/operation/FileReferenceCreate). К одному файлу
      можно добавлять несколько связанных объектов.

      #### Ограничения размера загружаемых файлов

      Допустимый размер одного файла ограничен 10 мегабайтами. При его превышении возвращается 413 ответ.

      Помимо этого, 413 ответ будет возвращен и когда достигается лимит суммы размера файлов пользователя.
  - name: mutation-locks
    x-displayName: Блокировки изменений
    description: |-
      После загрузки, файл может быть заблокирован от изменений.
      Каждая блокировка относится к какому-то объекту в системе,
      для которого файл становится зависимостью.
      Таких объектов-блокировок на файл может быть назначено несколько.
      И пока есть хотя бы одна активная блокировка, файл изменить нельзя.

      Блокировка может быть снята только системой,
      ответственной за объект, на который ссылается блок.
      Для представления этой ссылки, блок имеет два свойства:

        - `object_key` - символьное представление ключа зависимого объекта;
        - `object_namespace` - пространство имен ключа, определяющее тип сущности, которую ключ идентифицирует.
  - name: event-requests
    x-displayName: Заявки на мероприятия
  - name: events-read
    x-displayName: Чтение мероприятий
  - name: events-manage
    x-displayName: Управление мероприятиями
  - name: events-schema
    x-displayName: Схемы для мероприятий
  - name: events-deferred-notification
    x-displayName: Отложенные уведомления
    description: Отложенные уведомления для участников мероприятий.
  - name: events-diploma-settings
    x-displayName: Настройки дипломов для мероприятий
  - name: oauth
    x-displayName: OAuth2 провайдер
    description: |-
      Реализация авторизационного сервера OAuth2.
      [RFC6749](https://tools.ietf.org/html/rfc6749)
      [RFC7636](https://tools.ietf.org/html/rfc7636)
  - name: organizations
    x-displayName: Операции организаций
  - name: organization-subjects
    x-displayName: Операции с тематиками организаций
  - name: persons
    x-displayName: Персоны пользователей
  - name: user-signup
    x-displayName: Регистрация пользователя
  - name: user-profile
    x-displayName: Профиль пользователя
  - name: social-auths
    x-displayName: Внешние провайдеры авторизации
  - name: teams
    x-displayName: Команды пользователей
  - name: teams-schema
    x-displayName: Схемы для команд
  - name: user-consents
    x-displayName: Пользовательские согласия
    description: |-
      Параметр `user_id` в запросе должен содержать идентификатор аутентифицированного пользователя.
  - name: auth
    x-displayName: Аутентификация
    description: |-
      ## TalentOAuth

      Аутентификация токеном TalentOAuth пользователем Таланта.
      Передается в заголовке `Authorization: Bearer` в формате JWT.

      При использовании этой аутентификации,
      авторизация сервисом выполняется в отношении пользователя,
      авторизовавшего переданный токен.

      Для получения токена нужно воспользоваться [API OAuth2 провайдера](#tag/oauth).

      ## ClientCredentials

      Аутентификация учетными данными OAuth2 клиента TalentOAuth.
      В качестве `username` используется `client_id`, а в `password` - `client_secret`.
  - name: offset
    x-displayName: Пагинация
    description: |-
      Пагинация может быть представлена как параметром `offset`, так и параметром `id_offset`.
      Параметр `offset` позволяет указать кол-во объектов для пропуска из читаемой выборки.
      В `id_offset` указывается идентификатор, до которого включительно будут пропущены объекты.

      > Предпочтительно, когда есть возможность, использовать `id_offset`.
      > Также надо учитывать, что допустимое значение для `offset` имеет ограничения.

      > У `id_offset` тоже имеется ограничение - с ним не доступны варианты сортировки результатов,
      > за исключением вариантов `id_asc` и `id_desc`.
      > Для иных значений `order_by` будет возвращаться ответ `400 Bad Request`.
    x-traitTag: true

x-tagGroups:
  - name: Общие свойства API
    tags:
      - auth
      - offset
  - name: Авторизация
    tags:
      - oauth
  - name: Мероприятия
    tags:
      - events-schema
      - events-read
      - events-manage
      - events-deferred-notification
      - events-diploma-settings
      - event-requests
  - name: Организации
    tags:
      - organizations
      - organization-subjects
  - name: Пользователи
    tags:
      - persons
      - social-auths
      - user-signup
      - user-profile
      - user-consents
  - name: Команды
    tags:
      - teams
      - teams-schema
  - name: Файлы
    tags:
      - generic-files
      - mutation-locks

paths:
  /auth/login/{provider}:
    get:
      operationId: LoginSocialAuth
      summary: Авторизация во внешнем провайдере
      tags: [social-auths]
  /auth/complete/{provider}:
    get:
      operationId: CompleteSocialAuth
      summary: Завершение авторизации
      tags: [social-auths]
  /auth/disconnect/{provider}/{uid}:
    post:
      operationId: DisconnectSocialAuth
      summary: Удаление авторизации
      description: |-
        Удаление авторизации возможно только если это не единственный оставшийся у пользователя способ аутентификации под своей учетной записью.

        Не допускается параллельная обработка запросов на удаление, в случае появления такой гонки, будет возвращен 409 ответ.
      security: [TalentOAuth: [user]]
      tags: [social-auths]
  /auth/signup:
    get:
      operationId: SignupInitialData
      summary: Данные для предзаполнения формы регистрации
      tags: [user-signup]
    post:
      operationId: Signup
      summary: Регистрация пользователя
      tags: [user-signup]
  /auth/confirm-email/{uid}/{token}:
    post:
      operationId: ConfirmSignupEmail
      summary: Завершение регистрации пользователя подтверждением почты
      tags: [user-signup]
  /files:
    get:
      operationId: ListFileMeta
      summary: Список файлов
      description: |-
        #### Неаутентифицированный запрос публичных файлов

        Допускается запрос без аутентификации при соблюдении условий:
          - присутствуют значения параметра `file_id`
          - параметр `is_public` отсутствует либо содержит `true`

        При несоблюдении какого-либо из условий, возвращается `401` ответ.
      tags:
        - generic-files
      security:
        - TalentOAuth: [files:read]
        - {}
    post:
      operationId: CreateFileMeta
      summary: Создание файла
      tags:
        - generic-files
      security:
        - TalentOAuth: [files]
  /files/{file_id}:
    get:
      operationId: ReadFile
      summary: Получение ссылки на файл
      description: |-
        По-умолчанию возвращается в форме `307` ответа.
        С параметром `noredir=true` возвращается `200`.

        Чтение приватного файла требует прохождение авторизации.
        Аутентифицированный пользователь должен быть владельцем файла.
      tags:
        - generic-files
      security:
        - TalentOAuth: [files:read] # Непонятно нужен ли скоуп
        - {}
    put:
      operationId: UploadFile
      summary: Создание запроса на загрузку файла
      description: |-
        Позволяет повторно получить ссылку на загрузку того же файла или сформировать
        ссылку для загрузки новой версии файла (того же типа, но другого размера).
      tags:
        - generic-files
      security:
        - TalentOAuth: [files]
  /files/{file_id}/meta:
    get:
      operationId: ReadFileMeta
      summary: Чтение информации о файле
      description: |-
        Чтение приватного файла требует прохождение авторизации.
        Аутентифицированный пользователь должен быть владельцем файла.
      tags:
        - generic-files
      security:
        - TalentOAuth: [files:read] # Непонятно нужен ли скоуп
        - {}
    patch:
      operationId: UpdateFileMeta
      summary: Обновление информации о файле
      tags:
        - generic-files
      security:
        - TalentOAuth: [files]
  /files/{file_id}/confirm-upload:
    post:
      operationId: ConfirmFileUpload
      summary: Подтверждение загрузки файла
      tags:
        - generic-files
      security:
        - TalentOAuth: [files]
  /files/{file_id}/references/{object_id}:
    put:
      operationId: CreateFileReference
      summary: Добавление ссылки на файл
      tags:
        - generic-files
      security:
        - TalentOAuth: [files]
    delete:
      operationId: DeleteFileReference
      summary: Удаление ссылки на файл
      tags:
        - generic-files
      security:
        - TalentOAuth: [files]
  /events/diploma-settings:
    get:
      operationId: ListEventDiplomaSettings
      summary: Список настроек дипломов мероприятий
      tags:
        - events-diploma-settings
      security:
        - TalentOAuth: [events:read]
  /events:
    head:
      operationId: CountEvents
      summary: Счетчик мероприятий
      tags: [events-read]
    get:
      operationId: ListEvents
      summary: Список мероприятий
      description: |-
        Если не указан критерий сортировки результатов `order_by`,
        то он определяется в зависимости от указания других параметров.

        По-умолчанию результаты сортируются по идентификаторам в порядке возрастания (`id_asc`).
        Но если указан поисковый запрос и не используется параметр `id_offset`,
        то результаты сортируются по релевантности к поисковому запросу (`relevant`).

        При явном указании `order_by`, его значение должно соответствовать требованиям:
          - с параметром `id_offset` допускается только `order_by=id_asc`
          - вариант `order_by=relevant` доступен только при указании параметра `search`.
      tags: [events-read]
    post:
      operationId: CreateEvent
      summary: Добавление нового мероприятия
      security: [TalentOAuth: [events]]
      tags: [events-manage]
      description: |-
        При полном отсутствии в запросе массива `achievement_roles`,
        мероприятию назначаются роли достижений по-умолчанию.
        Пустой же массив приведет к созданию мероприятия без ролей.
  /events/addachievement:
    get:
      operationId: ListAddAchievementEvents
      summary: Список мероприятий для добавленя достижения
      description: Мероприятия, доступные для добавления достижения пользователем.
      tags: [events-read]
  /events/calendar:
    get:
      operationId: ListCalendarEvents
      summary: Список мероприятий для календаря
      tags: [events-read]
  /events/organizations/{organization_id}:
    get:
      operationId: ListOrganizationEvents
      summary: Список мероприятий организации
      tags: [events-read]
  /events/{event_id}:
    get:
      operationId: ReadEvent
      summary: Чтение свойств мероприятия
      tags: [events-read]
      description: |-
        По умолчанию возвращаются только метаданные.
        Для получения полного набора свойств используйте параметр `extend`.
  /events/{event_id}/deferred-notification:
    head:
      operationId: ExistsEventDeferredNotification
      summary: Проверка наличия отложенного уведомления
      tags: [events-deferred-notification]
    get:
      operationId: ReadEventDeferredNotification
      summary: Чтение отложенного уведомления
      tags: [events-deferred-notification]
      security:
        - TalentOAuth: [events:read]
    post:
      operationId: CreateEventDeferredNotification
      summary: Создание отложенного уведомления
      tags: [events-deferred-notification]
      security:
        - TalentOAuth: [events]
    patch:
      operationId: UpdateEventDeferredNotification
      summary: Изменение отложенного уведомления
      description: |-
        Если уведомление уже существует и оно находится в статусе `canceled`,
        оно будет переведено в статус `pending`.
      tags: [events-deferred-notification]
      security:
        - TalentOAuth: [events]
    delete:
      operationId: CancelEventDeferredNotification
      summary: Отмена запланированного уведомления
      description: |-
        Перевод уведомления из статуса `pending` в статус `canceled`.

        Если уведомление в статусе `pending` не найдено, будет возвращен `404` ответ.
      tags: [events-deferred-notification]
      security:
        - TalentOAuth: [events]
  /events/{event_id}/diploma-role/{role_id}:
    put:
      operationId: AddEventDiplomaRole
      summary: Добавление роли для диплома мероприятия
      tags:
        - events-diploma-settings
      security:
        - TalentOAuth: [events]
    delete:
      operationId: DeleteEventDiplomaRole
      summary: Удаление роли для диплома мероприятия
      tags:
        - events-diploma-settings
      security:
        - TalentOAuth: [events]
  /events/{event_id}/diploma-settings:
    get:
      operationId: ReadEventDiplomaSettings
      summary: Чтение настроек дипломов мероприятия
      tags:
        - events-diploma-settings
      security:
        - TalentOAuth: [events:read]
    post:
      operationId: CreateEventDiplomaSettings
      summary: Создание настроек дипломов мероприятия
      tags:
        - events-diploma-settings
      security:
        - TalentOAuth: [events]
    patch:
      operationId: UpdateEventDiplomaSettings
      summary: Обновление настроек дипломов мероприятия
      tags:
        - events-diploma-settings
      security:
        - TalentOAuth: [events]
  /events/{event_id}/fields:
    get:
      operationId: ListEventFields
      summary: Список полей анкеты мероприятия
      tags: [events-read]
  /events/{event_id}/limit:
    get:
      operationId: ReadEventLimit
      summary: Чтение лимитов мероприятия
      tags: [events-manage]
    post:
      operationId: CreateEventLimit
      summary: Создание лимитов мероприятия
      description: |-
        Лимиты могут существовать только в единичном кол-ве на мероприятие.
        Попытка создать больше будет возвращать `409` ответ.
      security: [TalentOAuth: [events]]
      tags: [events-manage]
    patch:
      operationId: UpdateEventLimit
      summary: Обновление лимитов мероприятия
      security: [TalentOAuth: [events]]
      tags: [events-manage]
    delete:
      operationId: DeleteEventLimit
      summary: Удаление лимитов мероприятия
      security: [TalentOAuth: [events]]
      tags: [events-manage]
  /events/{event_id}/signup:
    post:
      operationId: EventSignup
      summary: Создание заявки на мероприятие
      description: |-
        #### Аутентификация

        При выполнении запроса с аутентификацией,
        заявка создается для пользователя, с которым связан токен.

        Параметры, используемые для создания пользователя,
        в аутентифицированном запросе будут использованы для его обновления.

        Параметр `email` недопускается в аутентифицированных запросах.
      security: [TalentOAuth: [event-requests], {}]
      tags: [event-requests]
  /events/{event_id}/requests-files:
    get:
      operationId: ArchiveEventRequestsFiles
      summary: Скачивание архива файлов из заявок на мероприятие.
      description: 'Обязательно нужно указать один из параметров: `field_id` или `request_id`.'
      security: [TalentOAuth: [events]]
      tags: [events-manage]
  /event-brands:
    get:
      operationId: ListEventBrands
      summary: Список брендированных мероприятий
      tags: [events-read]
  /event-deferred-notification-templates/{name}:
    get:
      operationId: EventDeferredNotificationTemplateID
      summary: Идентификатор шаблона отложенного уведомления
      tags: [events-deferred-notification]
  /event-routes:
    get:
      operationId: ListEventRoutes
      summary: Список направлений мероприятий
      tags: [events-read]
  /mutation-locks/{object_namespace}/{object_key}:
    post:
      operationId: CreateMutationLock
      summary: Блокировка файлов от изменений
      description: |-
        Блокировки создаются только для файлов, принадлежащих пользователю.
        Чужие файлы, несуществующие файлы, а так же файлы,
        для которых блокировки уже имеются,
        будут пропущены и не возвращены в теле `201` ответа.
      tags: [mutation-locks]
      security:
        - TalentOAuth: [files]
    patch:
      operationId: PatchMutationLock
      summary: Изменение состояния блокировки
      description: |-
        Изначально блокировка создается в состоянии активной.
        После создания, состояние можно декактивировать и активировать обратно.

        > Неактивная блокировка равнозначна ее отсутствию.
      tags: [mutation-locks]
      security:
        - ClientCredentials: []
    delete:
      operationId: DeleteMutationLock
      summary: Удаление блокировки
      tags: [mutation-locks]
      security:
        - ClientCredentials: []
  /oauth/authorize:
    get:
      operationId: ValidateAuthorization
      summary: Валидация авторизационных параметров
      security: [TalentOAuth: []]
      tags: [oauth]
    post:
      operationId: AuthorizeClient
      summary: Авторизация клиента
      description: Пользователь авторизует доступ клиента к ресурсам пользователя
      security: [TalentOAuth: []]
      tags: [oauth]
  /oauth/issue-token:
    post:
      operationId: IssueAccessToken
      summary: Выдача токена доступа
      tags: [oauth]
  /organization-subjects:
    get:
      operationId: ListOrganizationSubjects
      summary: Список связей организаций и тематик
      tags: [organization-subjects]
    post:
      operationId: CreateOrganizationSubject
      summary: Добавление тематики для организации
      description: |-
        > Запрос необходимо выполнять от ментора или владельца организации,
        > указываемой в свойстве `organization_id` тела запроса.
      security: [TalentOAuth: [events]]
      tags: [organization-subjects]
  /organizations:
    get:
      operationId: ListOrganizations
      summary: Список организаций
      tags: [organizations]
  /organizations/{organization_id}/is-admin:
    post:
      operationId: IsOrganizationAdmin
      summary: Проверка наличия административных прав в организации
      security:
        - TalentOAuth: []
      tags: [organizations]
  /persons/{person_id}:
    get:
      operationId: ReadPerson
      summary: Чтение персоны пользователя
      tags:
        - persons
  /social-auths/{user_id}:
    get:
      operationId: ListSocialAuths
      summary: Список авторизаций пользователя в соц. сетях
      security:
        - TalentOAuth: [user:read]
        - ClientCredentials: []
      tags:
        - social-auths
  /subjects:
    get:
      operationId: ListSubjects
      summary: Список тематик для организаций
      tags: [organization-subjects]
  /teams/{team_id}:
    get:
      operationId: ReadTeam
      summary: Чтение параметров команды
      description: |-
        Часть данных возвращается только при наличии аутентификации и определенных прав у пользователя,
        от лица которого выполняется запрос.
      tags:
        - teams
      security:
        - TalentOAuth: [teams:read]
        - {}
    patch:
      operationId: UpdateTeam
      summary: Обновление параметров команды
      description: Доступно только для капитана команды и организатора мероприятия.
      tags:
        - teams
      security:
        - TalentOAuth: [teams]
  /teams/contact-validate:
    post:
      operationId: ValidateTeamContact
      summary: Валидация контактной ссылки
      tags:
        - teams
  /users/me:
    patch:
      operationId: UpdateAuthenticatedUser
      summary: Изменение аутентифицированного пользователя
      description: "> Операция еще не доступна"
      tags: [user-profile]
  /users/{user_id}/consents:
    get:
      operationId: ListUserConsents
      summary: Список согласий пользователя
      security: [TalentOAuth: [user:read]]
      tags: [user-consents]
  /users/{user_id}/consents/{kind}:
    head:
      operationId: CheckUserConsent
      summary: Проверка наличия согласия пользователя
      security: [TalentOAuth: [user:read]]
      tags: [user-consents]
    post:
      operationId: SubmitUserConsent
      summary: Фиксация согласия пользователя
      security: [TalentOAuth: [user]]
      tags: [user-consents]
components:
  securitySchemes:
    TalentOAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Аутентификация токеном TalentOAuth пользователем Таланта.
    ClientCredentials:
      type: http
      scheme: basic
      description: Аутентификация учетными данными OAuth2 клиента TalentOAuth.
